trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

stages:
  - stage: BuildAndTest
    displayName: "Build and Test"
    jobs:
      - job: Build
        displayName: "Install and Test"
        pool:
          name: 'ConorSelfHostedPool'

        steps:
          # Checkout code
          - task: Checkout@1
            displayName: "Checkout Code"

          # Set up Python
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'
              addToPath: true
            displayName: "Set up Python"

          # Install dependencies
          - script: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
            displayName: "Install Dependencies"

          # Run Unit Tests with Coverage
          - script: |
              coverage run -m unittest discover -s tests
              coverage report
            displayName: "Run Unit Tests with Coverage"
