trigger:
- develop  # Set to the 'develop' branch for testing

pool:
  name: ConorSelfHostedAgent  # Use your self-hosted agent

variables:
  pythonVersion: '3.10'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: $(pythonVersion)
    addToPath: true
  displayName: 'Set up Python'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    coverage run -m unittest discover -s tests -p "test_*.py"
    coverage report
  displayName: 'Run tests and generate coverage report'

- script: |
    bandit -r src/
  displayName: 'Run Bandit for static code analysis'
